### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by nils-van-zuijlen** [BDI-ENIB/vive-tracker#11]
Quelle licence mettre pour le projet ?

**Comment by nils-van-zuijlen** [comment]
Je propose la GNU AGPL v3 (Affero General Public License version 3)
https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License
https://gnu.org/licenses/agpl.html

<details>
<summary>Spoiler</summary>
Oui, déso, c'est la v3...
</details>

**Comment by Neopibox** [comment]
Comme indiqué dans la pull request qui a entrainé la création de cette issue :
"En soit, cet entête existe dans tous les fichiers créés à partir de PSoC Creator par défaut et je n'ai jamais réellement pris la peine de le changer.

Je considère néanmoins que mes contributions relève du logiciel libre, donc il est, en effet, nécessaire de préciser la licence. AGPL, c'est très bien, vu la notion de réseau qu'apporte le protocole Tonnerre."
