### ISSUE TITLE
Why use a LaTeX report ?

### ISSUE THREAD

**Issue by nils-van-zuijlen** [BDI-ENIB/vive-tracker#3]
Why is the documentation using the type `report` and not `book` as there are no `\part`.

Or else, change all chapters for parts.

**Comment by Neopibox** [comment]
We should now use book as a replacement for report, as the documentation may become insanely large.

This implies to review the structure of it as it should contains :
- introduction
- why we need such a positioning system.
- how other eurobot teams deal with this problem (rapid reviews of other systems)
- our idea
-- the lighthouse tech
-- overview
- hardware details
- "FPGA" details
- firmware details
- protocols
- tests (unit tests / qualification tests / robustness tests)
- real use
- conclusion
Appendix
- how to use beacons / trackers
- history

This structure can be adjusted to the needs.
