### ISSUE TITLE
Passage à des xBee S3

### ISSUE THREAD

**Issue by nils-van-zuijlen** [BDI-ENIB/vive-tracker#9]
Les xBee S1 ont été déclarés obsolètes par le fabricant, il est devenu quasi-impossible d'en trouver.

- [x] Commande des xBee : @nils-van-zuijlen 
    - [x] Réception des xBee
- [x] Prise en main des xBee
- [x] Adaptation du code pour les S3

**Comment by Neopibox** [comment]
Aucune adaptation du code n'est nécessaire pour discuter avec les xBee S3, du moment qu'ils utilisent la même norme radio (802.15.4) ce qui a valu le flashage d'un nouveau firmware. La configuration est pratiquement identique aux xBee S1.

Contrairement au S1, les S3 peuvent communiquer avec le microcontrôleur hôte (ici, le PSoC) en UART avec une vitesse de 115200 bauds et plus, en respectant parfaitement la norme (plus de problème de division de l'horloge interne).

L'augmentation du baudrate de la liaison UART nécessite une regénération de la circuiterie interne et du code bas niveau dans PSoC Creator.

Ci-joint, la configuration des xBee pour les trackers sur le "winterbot" (ou robot "principale") et le "summerbot" (ou "robot secondaire"). Celui présent sur le "winterbot" est configuré en tant que "coordinator" et l'autre, en tant qu' "end device".

**Comment by Neopibox** [comment]
Demande prise en compte dans la pull request #10.
